[package]
name = "candb-multi"
version = "0.11.6"
description = "Access to multiple canisters of CanDB database"
repository = "https://github.com/vporton/candb-multi"
keywords = [ "database", "databases", "query" ]
license = "MIT"

[dependencies]
candb = "1.0.7"
stable-rbtree = "1.0.0"
stablebuffer = "https://github.com/skilesare/StableBuffer#v0.2.0@110660769d11ba93c618dc4712525d20503bdc37"
base = "0.11.0"
