[package]
name = "CanDBMulti"
version = "0.9.12"
description = "Access to multiple canisters of CanDB database"
repository = "https://github.com/vporton/CanDBCache"
keywords = [ "database", "databases", "query" ]
license = "MIT"

[dependencies]
candb = "https://github.com/vporton/CanDB#no-blob"
stable-rbtree = "1.0.0"
stablebuffer = "https://github.com/skilesare/StableBuffer#v0.2.0@110660769d11ba93c618dc4712525d20503bdc37"
btree = "https://github.com/canscale/StableHeapBTreeMap#v0.3.3"
